# Generated by Django 5.1 on 2024-10-29 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_like_dislike'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like_dislike',
            old_name='posts',
            new_name='post',
        ),
    ]
